// <auto-generated />
namespace Twit.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Followers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Followers));
        
        string IMigrationMetadata.Id
        {
            get { return "201407021511452_Followers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
